# Generated by Django 5.2.6 on 2025-12-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_failedpayment_name_remove_payment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedpayment',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='failedpayment',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='address_line_one',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='message',
            field=models.TextField(blank=True, default='N/A'),
            preserve_default=False,
        ),
    ]
