# Generated by Django 5.2.6 on 2026-01-02 09:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_failedpayment_address_line_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedpayment',
            name='transaction_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
    ]
